server {
    listen 8081;
    
    server_name {SERVER_NAME};
    server_tokens off;
    
    proxy_buffering off;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
    proxy_read_timeout 600;
    send_timeout 600;
    
    root   /usr/share/nginx/run/html;
    index  index.html index.htm;

    error_page 404 /PageNotFound;
    error_page 403 =404 /PageNotFound;

    location / {

        set $cache_control "";
        set $pragma "";
        if ($uri = /index.html) {
            set $cache_control "no-store";
            set $pragma "no-cache";
        }
        if ($uri = /manifest.json) {
            set $cache_control "no-store";
            set $pragma "no-cache";
        }

        gzip on;
        gzip_vary on;
        gzip_proxied off;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_types text/plain text/css application/json application/javascript font/woff2 image/jpeg image/png image/x-icon;

        add_header X-Frame-Options {X_FRAME_OPTIONS};
        add_header X-Content-Type-Options {X_CONTENT_TYPE_OPTIONS};
        add_header X-XSS-Protection {X_XSS_PROTECTION};
        add_header Content-Security-Policy {CONTENT_SECURITY_POLICY};
        add_header Strict-Transport-Security {STRICT_TRANSPORT_SECURITY};
        add_header Cache-Control $cache_control;
        add_header Pragma $pragma;
        try_files $uri $uri/ /index.html;
    }

    location /esg/auth/ {
        proxy_pass {AUTH_HOST};
        client_max_body_size {CLIENT_MAX_BODY_SIZE};
    }

    location /esg/climaterisk/ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
        
        proxy_pass {API_HOST};
        client_max_body_size {CLIENT_MAX_BODY_SIZE};
        add_header Access-Control-Allow-Origin *;
    }

    location ~* \.(eot|otf|ttf|woff|woff2)$ {
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Credentials' 'true';
            add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        add_header Access-Control-Allow-Origin *;
    }

    error_page   500 502 503 504  /50x.html;

    location = /50x.html {
        root   /usr/share/nginx/run/html;
    }

    location = /healthcheck.html {
        root   /usr/share/nginx/run/html;
    }

}